services:
  postgres:
    image: postgres:15
    container_name: postgres-homolog
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: Tarefas
    volumes:
      - homolog_pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  backend-homolog:
    image: mcr.microsoft.com/dotnet/aspnet:8.0
    container_name: backend-homolog
    environment:
      - ASPNETCORE_URLS=http://+:80
    working_dir: /app
    volumes:
      - backend_homolog_volume:/app
      - frontend_homolog_volume:/usr/share/nginx/html
    command: >
      sh -c "dotnet /app/Tarefa.API.dll"
    ports:
      - "8082:80"
    depends_on:
      - postgres

  frontend-homolog:
    image: nginx:latest
    container_name: frontend-homolog
    volumes:
      - frontend_homolog_volume:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "8081:80"
    depends_on:
      - backend-homolog

volumes:
  homolog_pgdata:
  backend_homolog_volume:
  frontend_homolog_volume: