version: '3.8'

services:
  api:
    image: tarefas-api:latest
    container_name: tarefas-api-producao
    ports:
      - "5000:80"
    restart: unless-stopped
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: postgres-producao
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: Tarefas
    volumes:
      - producao_pgdata:/var/lib/postgresql/data

  nginx:
    image: nginx:latest
    container_name: nginx-producao
    ports:
      - "8090:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api
    restart: unless-stopped

volumes:
  producao_pgdata:
