version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres-prod
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: Tarefas
    volumes:
      - prod_pgdata:/var/lib/postgresql/data
    ports:
      - "5434:5432"

  backend-prod:
    image: mcr.microsoft.com/dotnet/aspnet:8.0
    container_name: backend-prod
    environment:
      - ASPNETCORE_URLS=http://+:80
    working_dir: /app
    volumes:
      - backend_prod_volume:/app
      - frontend_prod_volume:/usr/share/nginx/html
    command: >
      sh -c "dotnet /app/Tarefa.API.dll"
    ports:
      - "8091:80"
    depends_on:
      - postgres

  frontend-prod:
    image: nginx:latest
    container_name: frontend-prod
    volumes:
      - frontend_prod_volume:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8090:80"
    depends_on:
      - backend-prod

volumes:
  prod_pgdata:
  backend_prod_volume:
  frontend_prod_volume: